openapi: 3.0.1
info:
  title: ProMED API
  description: A RESTful API to process user queries to our databse of disease reports constructed from the ProMED website
  contact:
    email: z5258840@ad.unsw.edu.au
  version: 1.0.0
servers:
- url: "https://p5t20q9fz6.execute-api.ap-southeast-2.amazonaws.com/ProMedApi"
tags:
- name: live
  description: Check if the API server is live
- name: search
  description: Perform a search query on the ProMED disease report database
- name: report
  description: Access an individual disease report
- name: article
  description: Access an individual article
paths:
  /live:
    get:
      tags:
      - live
      summary: Check if the API server is live
      description: The server will return its live status and active version
      operationId: live
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Live'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Live_Error'
      x-swagger-router-controller: Live
  /search:
    get:
      tags:
      - search
      summary: Search the ProMED database
      description: Enter parameters to perform a search that will return all valid ProMED disease reports
      operationId: search
      parameters:
      - name: start_date
        in: query
        description: The start date of the period of interest for disease reports (must be in yyyy-MM-dd format)
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: '2022-03-05'
      - name: end_date
        in: query
        description: The end date of the period of interest for disease reports (must be in yyyy-MM-dd format)
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: '2022-03-07'
      - name: key_terms
        in: query
        description: A list of key terms to find in disease reports
        required: true
        style: form
        explode: true
        schema:
          type: array
          example:
          - measles
          - outbreak
          items:
            type: string
      - name: location
        in: query
        description: The location of interest for disease reports
        required: true
        style: form
        explode: true
        schema:
          type: string
          example: sydney
      - name: timezone
        in: query
        description: The timezone of interest for disease reports (optional)
        required: false
        style: form
        explode: true
        schema:
          type: string
          example: utc+10
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Search'
                x-content-type: application/json
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Search_Error'
                x-content-type: application/json
      x-swagger-router-controller: Search
  /report:
    get:
      tags:
      - report
      summary: Request a specific disease report
      description: Enter report ID to perform a request
      operationId: report
      parameters:
      - name: report_id
        in: query
        description: The ID of the requested report
        required: true
        style: form
        explode: true
        schema:
          type: integer
          example: 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Report_Error'
      x-swagger-router-controller: Report
  /article:
    get:
      tags:
      - article
      summary: Request a specific article
      description: Enter article ID to perform a request
      operationId: article
      parameters:
      - name: article_id
        in: query
        description: The ID of the requested article
        required: true
        style: form
        explode: true
        schema:
          type: integer
          example: 8701991
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article_Error'
      x-swagger-router-controller: Article
components:
  schemas:
    Search:
      type: object
      properties:
        url:
          type: string
          example: www.promed.com/measles-outbreak-sydney-2022
        date_of_publication:
          type: string
          example: 2022-01-05 xx:xx:xx
        headline:
          type: string
          example: Measles Outbreak in Sydney
        main_text:
          type: string
          example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent\
            \ convallis elit at leo finibus, a ultricies enim accumsan. Donec elementum\
            \ sagittis quam, ac dapibus erat aliquam id. Phasellus et libero vitae\
            \ mauris volutpat dignissim. Cras facilisis dui eleifend viverra sagittis.\
            \ Cras eu augue vitae elit vestibulum accumsan quis at dolor. Phasellus\
            \ blandit maximus mi, quis lacinia odio viverra ac. Phasellus dapibus\
            \ vel nunc eu  lobortis."
        reports:
          type: array
          items:
            $ref: '#/components/schemas/Search_Reports'
      example:
        reports:
        - event_date: 2022-01-05 xx:xx:xx to 2022-01-05
          diseases:
          - measles
          locations:
          - country: Australia
            location: Sydney
          syndromes:
          - outbreak
        - event_date: 2022-01-05 xx:xx:xx to 2022-01-05
          diseases:
          - measles
          locations:
          - country: Australia
            location: Sydney
          syndromes:
          - outbreak
        date_of_publication: 2022-01-05 xx:xx:xx
        main_text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent\
          \ convallis elit at leo finibus, a ultricies enim accumsan. Donec elementum\
          \ sagittis quam, ac dapibus erat aliquam id. Phasellus et libero vitae mauris\
          \ volutpat dignissim. Cras facilisis dui eleifend viverra sagittis. Cras\
          \ eu augue vitae elit vestibulum accumsan quis at dolor. Phasellus blandit\
          \ maximus mi, quis lacinia odio viverra ac. Phasellus dapibus vel nunc eu\
          \  lobortis."
        headline: Measles Outbreak in Sydney
        url: www.promed.com/measles-outbreak-sydney-2022
    Report:
      type: object
      properties:
        event_date:
          type: string
          example: 2022-01-05 xx:xx:xx to 2022-01-05
        locations:
          type: array
          items:
            $ref: '#/components/schemas/Search_Locations'
        diseases:
          type: array
          items:
            type: string
            example: measles
        syndromes:
          type: array
          items:
            type: string
            example: outbreak
      example:
        event_date: 2022-01-05 xx:xx:xx to 2022-01-05
        diseases:
        - measles
        locations:
        - country: Australia
          location: Sydney
        syndromes:
        - outbreak
    Article:
      type: object
      properties:
        url:
          type: string
          example: www.promed.com/measles-outbreak-sydney-2022
        date_of_publication:
          type: string
          example: 2022-01-05 xx:xx:xx
        headline:
          type: string
          example: Measles Outbreak in Sydney
        main_text:
          type: string
          example: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent\
            \ convallis elit at leo finibus, a ultricies enim accumsan. Donec elementum\
            \ sagittis quam, ac dapibus erat aliquam id. Phasellus et libero vitae\
            \ mauris volutpat dignissim. Cras facilisis dui eleifend viverra sagittis.\
            \ Cras eu augue vitae elit vestibulum accumsan quis at dolor. Phasellus\
            \ blandit maximus mi, quis lacinia odio viverra ac. Phasellus dapibus\
            \ vel nunc eu  lobortis."
      example:
        date_of_publication: 2022-01-05 xx:xx:xx
        main_text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent\
          \ convallis elit at leo finibus, a ultricies enim accumsan. Donec elementum\
          \ sagittis quam, ac dapibus erat aliquam id. Phasellus et libero vitae mauris\
          \ volutpat dignissim. Cras facilisis dui eleifend viverra sagittis. Cras\
          \ eu augue vitae elit vestibulum accumsan quis at dolor. Phasellus blandit\
          \ maximus mi, quis lacinia odio viverra ac. Phasellus dapibus vel nunc eu\
          \  lobortis."
        headline: Measles Outbreak in Sydney
        url: www.promed.com/measles-outbreak-sydney-2022
    Live:
      type: object
      properties:
        live:
          type: boolean
          example: true
        version:
          type: string
          example: 1.0.0
      example:
        version: 1.0.0
        live: true
    Live_Error:
      type: object
      properties:
        live:
          type: boolean
          example: false
        version:
          type: string
          example: 1.0.0
      example:
        version: 1.0.0
        live: false
    Search_Error:
      type: object
      properties:
        errorMessage:
          type: string
          example: 'Error: end_date before start_date'
        errorType:
          type: string
          example: Exception
        stackTrace:
          type: array
          items:
            type: string
            example: raise Exception
    Report_Error:
      type: object
      properties:
        errorMessage:
          type: string
          example: 'Error: invalid report ID'
        errorType:
          type: string
          example: Exception
        stackTrace:
          type: array
          items:
            type: string
            example: raise Exception
    Article_Error:
      type: object
      properties:
        errorMessage:
          type: string
          example: 'Error: invalid article ID'
        errorType:
          type: string
          example: Exception
        stackTrace:
          type: array
          items:
            type: string
            example: raise Exception
    Search_Locations:
      type: object
      properties:
        country:
          type: string
          example: Australia
        location:
          type: string
          example: Sydney
      example:
        country: Australia
        location: Sydney
    Search_Reports:
      type: object
      properties:
        event_date:
          type: string
          example: 2022-01-05 xx:xx:xx to 2022-01-05
        locations:
          type: array
          items:
            $ref: '#/components/schemas/Search_Locations'
        diseases:
          type: array
          items:
            type: string
            example: measles
        syndromes:
          type: array
          items:
            type: string
            example: outbreak
      example:
        event_date: 2022-01-05 xx:xx:xx to 2022-01-05
        diseases:
        - measles
        locations:
        - country: Australia
          location: Sydney
        syndromes:
        - outbreak
